"""add_workspace_configs

Revision ID: 644df6f463d7
Revises: 908aa2f89bc9
Create Date: 2026-06-08 07:30:26.988220
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '644df6f463d7'
down_revision: Union[str, None] = '908aa2f89bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_phone_number_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_access_token', sa.String(length=512), nullable=True),
    sa.Column('whatsapp_verify_token', sa.String(length=255), nullable=True),
    sa.Column('telegram_bot_token', sa.String(length=255), nullable=True),
    sa.Column('openai_api_key', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_configs_workspace_id'), 'workspace_configs', ['workspace_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_configs_workspace_id'), table_name='workspace_configs')
    op.drop_table('workspace_configs')
    # ### end Alembic commands ###
