"""add_bot_active_to_leads

Revision ID: 908aa2f89bc9
Revises: 3c729e694da2
Create Date: 2026-06-08 05:27:23.095256
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '908aa2f89bc9'
down_revision: Union[str, None] = '3c729e694da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('leads', sa.Column('bot_active', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.execute("UPDATE leads SET bot_active = true")
    op.alter_column('leads', 'bot_active', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'bot_active')
    # ### end Alembic commands ###
